name: Aric
favicon: null
layout_spectrum: 0.69018
typography_spectrum: 0.76013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a0b9f1'
    - '#5185c1'
    - '#25466f'
    - '#010506'
    - '#dedbf5'
  brandStrength: 0.13574056164361537
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
